# Generated by Django 5.1.4 on 2025-05-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
