# Generated by Django 5.1.4 on 2025-06-20 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='pet_report',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pet_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
