# Generated by Django 5.1.4 on 2025-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0002_alter_review_photo_alter_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_report',
            name='picture',
            field=models.URLField(blank=True, verbose_name='Картинка'),
        ),
    ]
