# Generated by Django 5.1.4 on 2025-06-20 21:07

import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0002_user_role_alter_blog_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_report',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='pet_reports/thumbnails/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='pet_report',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pet_reports/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])], verbose_name='Фото'),
        ),
    ]
