# Generated by Django 5.1.4 on 2025-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0003_alter_pet_report_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_report',
            name='picture',
            field=models.URLField(null=True, verbose_name='Картинка'),
        ),
    ]
