# Generated by Django 5.1.4 on 2025-06-20 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0003_pet_report_thumbnail_alter_pet_report_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_report',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='pet_report',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pet_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])], verbose_name='Фото'),
        ),
    ]
