# Generated by Django 5.1.4 on 2025-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalSearch', '0004_remove_pet_report_thumbnail_alter_pet_report_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, upload_to='reviews/'),
        ),
    ]
